source "https://rubygems.org"

gem "ruby_native_protocol", path: "../packages/ruby_native_protocol"
gem "ruby_native_ui", path: "../packages/ruby_native_ui"
gem "ruby_native_server", path: "../packages/ruby_native_server"
gem "ruby_native_cli", path: "../packages/ruby_native_cli"
gem "ruby_native", path: "../packages/ruby_native"
