/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>
#include <mruby/presym.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_3[12] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x4d,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_3, 1, (0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_3[] = "\x00\x0b\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_3 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_3}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_3_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_3;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_3 = {
12, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_3_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_3 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_3,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_3,
  &gem_mrblib_mruby_numeric_ext_proc_debug_3,
  12,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_4[23] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x4d,0x02,0x28,0x02,0x00,0x05,0x11,0x02,0x26,0x00,0x02,0x12,
0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_4, 1, (0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_4[] = "\x00\x16\x04\x01\x08\x01\x05\x02";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_4 = {
0, 278, 8, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_4}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_4_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_4;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_4 = {
23, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_4_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_4 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_4,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_4,
  &gem_mrblib_mruby_numeric_ext_proc_debug_4,
  23,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_5[12] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x50,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_5, 1, (0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_5[] = "\x00\x24\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_5 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_5}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_5_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_5;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_5 = {
12, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_5_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_5 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_5,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_5,
  &gem_mrblib_mruby_numeric_ext_proc_debug_5,
  12,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_6[12] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x06,0x03,0x4e,0x02,0x3d,0x02,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_6, 1, (0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_6[] = "\x00\x2e\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_6 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_6}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_6_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_6;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_6 = {
12, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_6_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_6 = {
  2,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_6,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_6,
  &gem_mrblib_mruby_numeric_ext_proc_debug_6,
  12,0,0,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_7[5] = {
0x39,0x00,0x00,0x00,0x42,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_7, 1, (0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_7[] = "\x00\x3b\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_7 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_7}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_7_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_7;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_7 = {
5, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_7_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_7 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_7,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_7,
  &gem_mrblib_mruby_numeric_ext_proc_debug_7,
  5,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_numeric_ext_proc_reps_1[5] = {
  &gem_mrblib_mruby_numeric_ext_proc_irep_3,
  &gem_mrblib_mruby_numeric_ext_proc_irep_4,
  &gem_mrblib_mruby_numeric_ext_proc_irep_5,
  &gem_mrblib_mruby_numeric_ext_proc_irep_6,
  &gem_mrblib_mruby_numeric_ext_proc_irep_7,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_1, 5, (MRB_SYM_Q(zero), MRB_SYM_Q(nonzero), MRB_SYM_Q(positive), MRB_SYM_Q(negative), MRB_SYM_Q(integer), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_1[22] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x3d,0x00,};
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_1[] = "\x00\x0b\x04\x0b\x04\x0e\x04\x0a\x04\x0d";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_1 = {
0, 278, 10, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_1}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_1_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_1;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_1 = {
22, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_1_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_1 = {
  1,1,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_1,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_1,gem_mrblib_mruby_numeric_ext_proc_reps_1,
  NULL,					/* lv */
  &gem_mrblib_mruby_numeric_ext_proc_debug_1,
  22,0,5,5,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_30, 1, (MRB_OPSYM(and), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_30[18] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x01,0x04,0x01,0x4d,0x03,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_30, 2, (MRB_SYM(mask), 0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_30[] = "\x00\x47\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_30 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_30}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_30_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_30;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_30 = {
18, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_30_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_30 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_30,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_30,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_30,
  &gem_mrblib_mruby_numeric_ext_proc_debug_30,
  18,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_31, 2, (MRB_OPSYM(and), MRB_OPSYM(neq), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_31[19] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x06,0x04,0x32,0x03,0x01,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_31, 2, (MRB_SYM(mask), 0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_31[] = "\x00\x51\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_31 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_31}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_31_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_31;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_31 = {
19, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_31_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_31 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_31,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_31,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_31,
  &gem_mrblib_mruby_numeric_ext_proc_debug_31,
  19,0,2,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_32, 1, (MRB_OPSYM(and), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_32[17] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x2f,0x03,0x00,0x01,0x06,0x04,0x4d,0x03,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_32, 2, (MRB_SYM(mask), 0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_32[] = "\x00\x5b\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_32 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_32}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_32_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_32;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_32 = {
17, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_32_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_32 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_32,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_32,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_32,
  &gem_mrblib_mruby_numeric_ext_proc_debug_32,
  17,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_33, 2, (MRB_OPSYM(minus), MRB_SYM(div), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_33[21] = {
0x39,0x04,0x00,0x00,0x01,0x04,0x01,0x32,0x04,0x00,0x00,0x2f,0x03,0x01,0x01,0x32,0x03,0x00,0x00,0x3d,
0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_33, 2, (MRB_SYM(other), 0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_33[] = "\x00\x6d\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_33 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_33}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_33_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_33;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_33 = {
21, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_33_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_33 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_33,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_33,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_33,
  &gem_mrblib_mruby_numeric_ext_proc_debug_33,
  21,0,2,0,0
};
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_34[5] = {
0x39,0x00,0x00,0x00,0x41,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_lv_34, 1, (0,), const);
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_34[] = "\x00\x7a\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_34 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_34}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_34_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_34;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_34 = {
5, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_34_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_34 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_34,
  NULL,NULL,NULL,
  gem_mrblib_mruby_numeric_ext_proc_lv_34,
  &gem_mrblib_mruby_numeric_ext_proc_debug_34,
  5,0,0,0,0
};
static const mrb_irep *gem_mrblib_mruby_numeric_ext_proc_reps_2[5] = {
  &gem_mrblib_mruby_numeric_ext_proc_irep_30,
  &gem_mrblib_mruby_numeric_ext_proc_irep_31,
  &gem_mrblib_mruby_numeric_ext_proc_irep_32,
  &gem_mrblib_mruby_numeric_ext_proc_irep_33,
  &gem_mrblib_mruby_numeric_ext_proc_irep_34,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_2, 5, (MRB_SYM_Q(allbits), MRB_SYM_Q(anybits), MRB_SYM_Q(nobits), MRB_SYM(ceildiv), MRB_SYM_Q(integer), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_2[22] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x3d,0x01,};
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_2[] = "\x00\x47\x04\x0a\x04\x0a\x04\x12\x04\x0d";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_2 = {
0, 278, 10, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_2}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_2_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_2;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_2 = {
22, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_2_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_2 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_2,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_2,gem_mrblib_mruby_numeric_ext_proc_reps_2,
  NULL,					/* lv */
  &gem_mrblib_mruby_numeric_ext_proc_debug_2,
  22,0,5,5,0
};
static const mrb_irep *gem_mrblib_mruby_numeric_ext_proc_reps_0[2] = {
  &gem_mrblib_mruby_numeric_ext_proc_irep_1,
  &gem_mrblib_mruby_numeric_ext_proc_irep_2,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_numeric_ext_proc_syms_0, 2, (MRB_SYM(Numeric), MRB_SYM(Integer), ), const);
static const mrb_code gem_mrblib_mruby_numeric_ext_proc_iseq_0[23] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x11,0x01,0x11,0x02,0x67,0x01,0x01,0x69,0x01,0x01,
0x3d,0x01,0x76,};
static const char gem_mrblib_mruby_numeric_ext_proc_debug_lines_0[] = "\x00\x01\x0a\x3f";
static mrb_irep_debug_info_file gem_mrblib_mruby_numeric_ext_proc_debug_file_0 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_numeric_ext_proc_debug_lines_0}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_numeric_ext_proc_debug_file_0_ = &gem_mrblib_mruby_numeric_ext_proc_debug_file_0;
static mrb_irep_debug_info gem_mrblib_mruby_numeric_ext_proc_debug_0 = {
23, 1, &gem_mrblib_mruby_numeric_ext_proc_debug_file_0_};
static const mrb_irep gem_mrblib_mruby_numeric_ext_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_numeric_ext_proc_iseq_0,
  NULL,gem_mrblib_mruby_numeric_ext_proc_syms_0,gem_mrblib_mruby_numeric_ext_proc_reps_0,
  NULL,					/* lv */
  &gem_mrblib_mruby_numeric_ext_proc_debug_0,
  23,0,2,2,0
};
static
const struct RProc gem_mrblib_mruby_numeric_ext_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_numeric_ext_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_numeric_ext_proc_init_syms(mrb_state *mrb)
{
  gem_mrblib_mruby_numeric_ext_proc_debug_file_3.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_4.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_5.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_6.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_7.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_1.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_30.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_31.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_32.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_33.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_34.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_2.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
  gem_mrblib_mruby_numeric_ext_proc_debug_file_0.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb");
}
void mrb_mruby_numeric_ext_gem_init(mrb_state *mrb);
void mrb_mruby_numeric_ext_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_numeric_ext_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_numeric_ext_proc_init_syms(mrb);
  mrb_mruby_numeric_ext_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_numeric_ext_proc);
}

void GENERATED_TMP_mrb_mruby_numeric_ext_gem_final(mrb_state *mrb) {
  mrb_mruby_numeric_ext_gem_final(mrb);
}
