# frozen_string_literal: true

module Ruflet
  module UI
    module SharedControlForwarders
      def control(type, **props, &block) = control_delegate.control(type, **props, &block)
      def widget(type, **props, &block) = control_delegate.widget(type, **props, &block)
      def service(type, **props, &block) = control_delegate.service(type, **props, &block)
      def view(**props, &block) = control_delegate.view(**props, &block)
      def column(**props, &block) = control_delegate.column(**props, &block)
      def center(**props, &block) = control_delegate.center(**props, &block)
      def row(**props, &block) = control_delegate.row(**props, &block)
      def stack(**props, &block) = control_delegate.stack(**props, &block)
      def grid_view(**props, &block) = control_delegate.grid_view(**props, &block)
      def gridview(**props, &block) = control_delegate.gridview(**props, &block)
      def container(**props, &block) = control_delegate.container(**props, &block)
      def gesture_detector(**props, &block) = control_delegate.gesture_detector(**props, &block)
      def gesturedetector(**props, &block) = control_delegate.gesturedetector(**props, &block)
      def draggable(**props, &block) = control_delegate.draggable(**props, &block)
      def drag_target(**props, &block) = control_delegate.drag_target(**props, &block)
      def dragtarget(**props, &block) = control_delegate.dragtarget(**props, &block)
      def text(value = nil, **props) = control_delegate.text(value, **props)
      def button(**props) = control_delegate.button(**props)
      def elevated_button(**props) = control_delegate.elevated_button(**props)
      def text_button(**props) = control_delegate.text_button(**props)
      def textbutton(**props) = control_delegate.textbutton(**props)
      def filled_button(**props) = control_delegate.filled_button(**props)
      def filledbutton(**props) = control_delegate.filledbutton(**props)
      def icon_button(**props) = control_delegate.icon_button(**props)
      def iconbutton(**props) = control_delegate.iconbutton(**props)
      def text_field(**props) = control_delegate.text_field(**props)
      def textfield(**props) = control_delegate.textfield(**props)
      def checkbox(**props) = control_delegate.checkbox(**props)
      def radio(**props) = control_delegate.radio(**props)
      def radio_group(**props) = control_delegate.radio_group(**props)
      def radiogroup(**props) = control_delegate.radiogroup(**props)
      def alert_dialog(**props) = control_delegate.alert_dialog(**props)
      def alertdialog(**props) = control_delegate.alertdialog(**props)
      def snack_bar(**props) = control_delegate.snack_bar(**props)
      def snackbar(**props) = control_delegate.snackbar(**props)
      def bottom_sheet(**props) = control_delegate.bottom_sheet(**props)
      def bottomsheet(**props) = control_delegate.bottomsheet(**props)
      def markdown(value = nil, **props) = control_delegate.markdown(value, **props)
      def icon(**props) = control_delegate.icon(**props)
      def image(src = nil, **props) = control_delegate.image(src, **props)
      def fab(content = nil, **props) = control_delegate.fab(content, **props)
      def app_bar(**props) = control_delegate.app_bar(**props)
      def appbar(**props) = control_delegate.appbar(**props)
      def clipboard(**props) = control_delegate.clipboard(**props)
      def floating_action_button(**props) = control_delegate.floating_action_button(**props)
      def floatingactionbutton(**props) = control_delegate.floatingactionbutton(**props)
      def tabs(**props, &block) = control_delegate.tabs(**props, &block)
      def tab(**props, &block) = control_delegate.tab(**props, &block)
      def tab_bar(**props, &block) = control_delegate.tab_bar(**props, &block)
      def tabbar(**props, &block) = control_delegate.tabbar(**props, &block)
      def tab_bar_view(**props, &block) = control_delegate.tab_bar_view(**props, &block)
      def tabbarview(**props, &block) = control_delegate.tabbarview(**props, &block)
      def navigation_bar(**props, &block) = control_delegate.navigation_bar(**props, &block)
      def navigationbar(**props, &block) = control_delegate.navigationbar(**props, &block)
      def navigation_bar_destination(**props, &block) = control_delegate.navigation_bar_destination(**props, &block)
      def navigationbardestination(**props, &block) = control_delegate.navigationbardestination(**props, &block)
      def bar_chart(**props) = control_delegate.bar_chart(**props)
      def barchart(**props) = control_delegate.barchart(**props)
      def bar_chart_group(**props) = control_delegate.bar_chart_group(**props)
      def barchartgroup(**props) = control_delegate.barchartgroup(**props)
      def bar_chart_rod(**props) = control_delegate.bar_chart_rod(**props)
      def barchartrod(**props) = control_delegate.barchartrod(**props)
      def bar_chart_rod_stack_item(**props) = control_delegate.bar_chart_rod_stack_item(**props)
      def barchartrodstackitem(**props) = control_delegate.barchartrodstackitem(**props)
      def line_chart(**props) = control_delegate.line_chart(**props)
      def linechart(**props) = control_delegate.linechart(**props)
      def line_chart_data(**props) = control_delegate.line_chart_data(**props)
      def linechartdata(**props) = control_delegate.linechartdata(**props)
      def line_chart_data_point(**props) = control_delegate.line_chart_data_point(**props)
      def linechartdatapoint(**props) = control_delegate.linechartdatapoint(**props)
      def pie_chart(**props) = control_delegate.pie_chart(**props)
      def piechart(**props) = control_delegate.piechart(**props)
      def pie_chart_section(**props) = control_delegate.pie_chart_section(**props)
      def piechartsection(**props) = control_delegate.piechartsection(**props)
      def candlestick_chart(**props) = control_delegate.candlestick_chart(**props)
      def candlestickchart(**props) = control_delegate.candlestickchart(**props)
      def candlestick_chart_spot(**props) = control_delegate.candlestick_chart_spot(**props)
      def candlestickchartspot(**props) = control_delegate.candlestickchartspot(**props)
      def radar_chart(**props) = control_delegate.radar_chart(**props)
      def radarchart(**props) = control_delegate.radarchart(**props)
      def radar_chart_title(**props) = control_delegate.radar_chart_title(**props)
      def radarcharttitle(**props) = control_delegate.radarcharttitle(**props)
      def radar_data_set(**props) = control_delegate.radar_data_set(**props)
      def radardataset(**props) = control_delegate.radardataset(**props)
      def radar_data_set_entry(**props) = control_delegate.radar_data_set_entry(**props)
      def radardatasetentry(**props) = control_delegate.radardatasetentry(**props)
      def scatter_chart(**props) = control_delegate.scatter_chart(**props)
      def scatterchart(**props) = control_delegate.scatterchart(**props)
      def scatter_chart_spot(**props) = control_delegate.scatter_chart_spot(**props)
      def scatterchartspot(**props) = control_delegate.scatterchartspot(**props)
      def chart_axis(**props) = control_delegate.chart_axis(**props)
      def chartaxis(**props) = control_delegate.chartaxis(**props)
      def chart_axis_label(**props) = control_delegate.chart_axis_label(**props)
      def chartaxislabel(**props) = control_delegate.chartaxislabel(**props)
      def web_view(**props) = control_delegate.web_view(**props)
      def webview(**props) = control_delegate.webview(**props)
      def cupertino_button(**props) = control_delegate.cupertino_button(**props)
      def cupertinobutton(**props) = control_delegate.cupertinobutton(**props)
      def cupertino_filled_button(**props) = control_delegate.cupertino_filled_button(**props)
      def cupertinofilledbutton(**props) = control_delegate.cupertinofilledbutton(**props)
      def cupertino_text_field(**props) = control_delegate.cupertino_text_field(**props)
      def cupertinotextfield(**props) = control_delegate.cupertinotextfield(**props)
      def cupertino_switch(**props) = control_delegate.cupertino_switch(**props)
      def cupertinoswitch(**props) = control_delegate.cupertinoswitch(**props)
      def cupertino_slider(**props) = control_delegate.cupertino_slider(**props)
      def cupertinoslider(**props) = control_delegate.cupertinoslider(**props)
      def cupertino_alert_dialog(**props) = control_delegate.cupertino_alert_dialog(**props)
      def cupertinoalertdialog(**props) = control_delegate.cupertinoalertdialog(**props)
      def cupertino_action_sheet(**props) = control_delegate.cupertino_action_sheet(**props)
      def cupertinoactionsheet(**props) = control_delegate.cupertinoactionsheet(**props)
      def cupertino_dialog_action(**props) = control_delegate.cupertino_dialog_action(**props)
      def cupertinodialogaction(**props) = control_delegate.cupertinodialogaction(**props)
      def cupertino_navigation_bar(**props) = control_delegate.cupertino_navigation_bar(**props)
      def cupertinonavigationbar(**props) = control_delegate.cupertinonavigationbar(**props)
      def duration(**parts) = control_delegate.duration(**parts)

      private

      def control_delegate
        raise NotImplementedError, "control_delegate must be implemented by the including/extended context"
      end
    end
  end
end
