#ifndef RUFLET_ONIGMO_CONFIG_H
#define RUFLET_ONIGMO_CONFIG_H

#define HAVE_ALLOCA_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1

#define SIZEOF_INT __SIZEOF_INT__
#define SIZEOF_LONG __SIZEOF_LONG__
#define SIZEOF_LONG_LONG __SIZEOF_LONG_LONG__
#define SIZEOF_SHORT __SIZEOF_SHORT__
#define SIZEOF_VOIDP __SIZEOF_POINTER__

#define PACKAGE "onigmo"
#define PACKAGE_NAME "onigmo"
#define PACKAGE_STRING "onigmo 6.2.0"
#define PACKAGE_VERSION "6.2.0"
#define VERSION "6.2.0"

#endif
