name: ruby_runtime
description: Embed Ruflet's mruby runtime in Flutter apps for Android, iOS, and macOS.
version: 0.0.2
homepage: https://github.com/AdamMusa/ruflet
repository: https://github.com/AdamMusa/ruflet
issue_tracker: https://github.com/AdamMusa/ruflet/issues
documentation: https://github.com/AdamMusa/ruflet/tree/main/ruby_runtime

topics:
  - ruby
  - mruby
  - flutter-plugin
  - desktop

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.izeesoft.ruby_runtime
        pluginClass: MrubyRuntimePlugin
      ios:
        pluginClass: MrubyRuntimePlugin
      macos:
        pluginClass: RubyRuntimeMacosPlugin
