/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>
#include <mruby/presym.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_2, 4, (MRB_SYM(each), MRB_SYM(to_enum), MRB_SYM(read), MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_2[48] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x01,0x04,0x02,0x27,0x04,0x00,0x09,0x10,0x05,0x00,0x2f,0x04,0x01,
0x01,0x3d,0x04,0x30,0x04,0x02,0x01,0x03,0x04,0x28,0x04,0x00,0x0e,0x00,0x01,0x04,0x02,0x01,0x05,0x03,
0x32,0x04,0x03,0x01,0x26,0xff,0xe8,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_lv_2, 3, (0,MRB_SYM(block), MRB_SYM(s), ), const);
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_2 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_2,
  NULL,gem_mrblib_mruby_dir_proc_syms_2,NULL,
  gem_mrblib_mruby_dir_proc_lv_2,
  NULL,					/* debug_info */
  48,0,4,0,0
};
static const mrb_irep_pool gem_mrblib_mruby_dir_proc_pool_3[2] = {
{IREP_TT_SSTR|(1<<2), {"\x2e"}},
{IREP_TT_SSTR|(2<<2), {"\x2e\x2e"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_3, 4, (MRB_SYM(each_child), MRB_SYM(to_enum), MRB_SYM(read), MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_3[72] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x01,0x04,0x02,0x27,0x04,0x00,0x09,0x10,0x05,0x00,0x2f,0x04,0x01,
0x01,0x3d,0x04,0x30,0x04,0x02,0x01,0x03,0x04,0x28,0x04,0x00,0x26,0x00,0x01,0x04,0x03,0x5c,0x05,0x00,
0x4d,0x04,0x27,0x04,0x00,0x08,0x01,0x04,0x03,0x5c,0x05,0x01,0x4d,0x04,0x27,0x04,0x00,0x0a,0x01,0x04,
0x02,0x01,0x05,0x03,0x32,0x04,0x03,0x01,0x26,0xff,0xd0,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_lv_3, 3, (0,MRB_SYM(block), MRB_SYM(s), ), const);
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_3 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_3,
  gem_mrblib_mruby_dir_proc_pool_3,gem_mrblib_mruby_dir_proc_syms_3,NULL,
  gem_mrblib_mruby_dir_proc_lv_3,
  NULL,					/* debug_info */
  72,2,4,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_14, 1, (MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_14[17] = {
0x39,0x04,0x00,0x00,0x01,0x03,0x01,0x21,0x04,0x03,0x00,0x34,0x03,0x00,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_lv_14, 2, (MRB_SYM(d), 0,), const);
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_14 = {
  3,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_14,
  NULL,gem_mrblib_mruby_dir_proc_syms_14,NULL,
  gem_mrblib_mruby_dir_proc_lv_14,
  NULL,					/* debug_info */
  17,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_dir_proc_reps_11[1] = {
  &gem_mrblib_mruby_dir_proc_irep_14,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_11, 3, (MRB_SYM(foreach), MRB_SYM(to_enum), MRB_SYM(open), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_11[38] = {
0x39,0x04,0x00,0x01,0x01,0x03,0x02,0x01,0x04,0x03,0x27,0x04,0x00,0x0c,0x10,0x05,0x00,0x01,0x06,0x01,
0x2f,0x04,0x01,0x02,0x3d,0x04,0x01,0x05,0x01,0x62,0x06,0x00,0x31,0x04,0x02,0x01,0x3d,0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_lv_11, 3, (MRB_SYM(path), 0,MRB_SYM(block), ), const);
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_11 = {
  4,8,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_11,
  NULL,gem_mrblib_mruby_dir_proc_syms_11,gem_mrblib_mruby_dir_proc_reps_11,
  gem_mrblib_mruby_dir_proc_lv_11,
  NULL,					/* debug_info */
  38,0,3,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_12, 4, (MRB_SYM(new), MRB_SYM(call), MRB_SYM(close), MRB_SYM(IOError), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_12[105] = {
0x39,0x04,0x00,0x01,0x01,0x03,0x02,0x01,0x05,0x03,0x28,0x05,0x00,0x38,0x01,0x06,0x01,0x2f,0x05,0x00,
0x01,0x01,0x04,0x05,0x01,0x05,0x03,0x01,0x06,0x04,0x32,0x05,0x01,0x01,0x2b,0x07,0x01,0x08,0x04,0x33,
0x08,0x02,0x26,0x00,0x14,0x2b,0x08,0x1d,0x09,0x03,0x2c,0x08,0x09,0x27,0x09,0x00,0x03,0x26,0x00,0x03,
0x26,0x00,0x02,0x2d,0x08,0x2d,0x07,0x26,0x00,0x07,0x01,0x06,0x01,0x2f,0x05,0x00,0x01,0x3d,0x05,0x01,
0x00,0x00,0x00,0x18,0x00,0x00,0x00,0x22,0x00,0x00,0x00,0x22,0x00,0x00,0x00,0x00,0x24,0x00,0x00,0x00,
0x2a,0x00,0x00,0x00,0x2d,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_lv_12, 4, (MRB_SYM(path), 0,MRB_SYM(block), MRB_SYM(d), ), const);
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_12 = {
  5,10,2,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_12,
  NULL,gem_mrblib_mruby_dir_proc_syms_12,NULL,
  gem_mrblib_mruby_dir_proc_lv_12,
  NULL,					/* debug_info */
  79,0,4,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_13, 3, (MRB_SYM(getwd), MRB_SYM(_chdir), MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_13[73] = {
0x39,0x04,0x00,0x01,0x01,0x03,0x02,0x01,0x05,0x03,0x28,0x05,0x00,0x25,0x30,0x05,0x00,0x01,0x04,0x05,
0x01,0x06,0x01,0x2f,0x05,0x01,0x01,0x01,0x05,0x03,0x01,0x06,0x01,0x32,0x05,0x02,0x01,0x2b,0x07,0x01,
0x09,0x04,0x2f,0x08,0x01,0x01,0x2d,0x07,0x26,0x00,0x07,0x01,0x06,0x01,0x2f,0x05,0x01,0x01,0x3d,0x05,
0x01,0x00,0x00,0x00,0x14,0x00,0x00,0x00,0x25,0x00,0x00,0x00,0x25,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_lv_13, 4, (MRB_SYM(path), 0,MRB_SYM(block), MRB_SYM(wd), ), const);
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_13 = {
  5,11,1,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_13,
  NULL,gem_mrblib_mruby_dir_proc_syms_13,NULL,
  gem_mrblib_mruby_dir_proc_lv_13,
  NULL,					/* debug_info */
  60,0,3,0,0
};
static const mrb_irep *gem_mrblib_mruby_dir_proc_reps_4[3] = {
  &gem_mrblib_mruby_dir_proc_irep_11,
  &gem_mrblib_mruby_dir_proc_irep_12,
  &gem_mrblib_mruby_dir_proc_irep_13,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_4, 10, (MRB_SYM(foreach), MRB_SYM(open), MRB_SYM(chdir), MRB_SYM_Q(exists), MRB_SYM_Q(exist), MRB_SYM(pwd), MRB_SYM(getwd), MRB_SYM(rmdir), MRB_SYM(delete), MRB_SYM(unlink), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_4[25] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6d,0x03,0x04,0x6d,0x05,0x06,0x6d,0x07,
0x08,0x6d,0x09,0x08,0x40,};
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_4 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_4,
  NULL,gem_mrblib_mruby_dir_proc_syms_4,gem_mrblib_mruby_dir_proc_reps_4,
  NULL,					/* lv */
  NULL,					/* debug_info */
  25,0,10,3,0
};
static const mrb_irep *gem_mrblib_mruby_dir_proc_reps_1[3] = {
  &gem_mrblib_mruby_dir_proc_irep_2,
  &gem_mrblib_mruby_dir_proc_irep_3,
  &gem_mrblib_mruby_dir_proc_irep_4,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_1, 8, (MRB_SYM(Enumerable), MRB_SYM(include), MRB_SYM(each), MRB_SYM(each_child), MRB_SYM(pos), MRB_SYM(tell), MRB_SYM_E(pos), MRB_SYM(seek), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_1[30] = {
0x1d,0x02,0x00,0x2f,0x01,0x01,0x01,0x6b,0x01,0x02,0x00,0x6b,0x01,0x03,0x01,0x6d,0x04,0x05,0x6d,0x06,
0x07,0x12,0x01,0x6f,0x01,0x69,0x01,0x02,0x3d,0x01,};
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_1 = {
  1,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_1,
  NULL,gem_mrblib_mruby_dir_proc_syms_1,gem_mrblib_mruby_dir_proc_reps_1,
  NULL,					/* lv */
  NULL,					/* debug_info */
  30,0,8,3,0
};
static const mrb_irep *gem_mrblib_mruby_dir_proc_reps_0[1] = {
  &gem_mrblib_mruby_dir_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_dir_proc_syms_0, 1, (MRB_SYM(Dir), ), const);
static const mrb_code gem_mrblib_mruby_dir_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const mrb_irep gem_mrblib_mruby_dir_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_dir_proc_iseq_0,
  NULL,gem_mrblib_mruby_dir_proc_syms_0,gem_mrblib_mruby_dir_proc_reps_0,
  NULL,					/* lv */
  NULL,					/* debug_info */
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_dir_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_dir_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_dir_proc_init_syms(mrb_state *mrb)
{
}
void mrb_mruby_dir_gem_init(mrb_state *mrb);
void mrb_mruby_dir_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_dir_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_dir_proc_init_syms(mrb);
  mrb_mruby_dir_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_dir_proc);
}

void GENERATED_TMP_mrb_mruby_dir_gem_final(mrb_state *mrb) {
  mrb_mruby_dir_gem_final(mrb);
}
