/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>
#include <mruby/presym.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_7, 1, (MRB_SYM(push), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_7[44] = {
0x39,0x04,0x00,0x00,0x21,0x03,0x04,0x00,0x06,0x04,0x4f,0x03,0x28,0x03,0x00,0x04,0x11,0x03,0x43,0x03,
0x21,0x03,0x05,0x00,0x01,0x04,0x01,0x32,0x03,0x00,0x01,0x21,0x03,0x04,0x00,0x48,0x03,0x01,0x22,0x03,
0x04,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_lv_7, 2, (MRB_SYM(i), 0,), const);
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_7[] = "\x00\x16\x04\x01\x10\x01\x0b\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_7 = {
0, 278, 8, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_7}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_7_ = &gem_mrblib_mruby_range_ext_proc_debug_file_7;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_7 = {
44, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_7_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_7 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_7,
  NULL,gem_mrblib_mruby_range_ext_proc_syms_7,NULL,
  gem_mrblib_mruby_range_ext_proc_lv_7,
  &gem_mrblib_mruby_range_ext_proc_debug_7,
  44,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_range_ext_proc_reps_2[1] = {
  &gem_mrblib_mruby_range_ext_proc_irep_7,
};
static const mrb_irep_pool gem_mrblib_mruby_range_ext_proc_pool_2[4] = {
{IREP_TT_SSTR|(47<<2), {"\x63\x61\x6e\x6e\x6f\x74\x20\x67\x65\x74\x20\x74\x68\x65\x20\x66\x69\x72\x73\x74\x20\x65\x6c\x65\x6d\x65\x6e\x74\x20\x6f\x66\x20\x62\x65\x67\x69\x6e\x6c\x65\x73\x73\x20\x72\x61\x6e\x67\x65"}},
{IREP_TT_SSTR|(33<<2), {"\x77\x72\x6f\x6e\x67\x20\x6e\x75\x6d\x62\x65\x72\x20\x6f\x66\x20\x61\x72\x67\x75\x6d\x65\x6e\x74\x73\x20\x28\x67\x69\x76\x65\x6e\x20"}},
{IREP_TT_SSTR|(13<<2), {"\x2c\x20\x65\x78\x70\x65\x63\x74\x65\x64\x20\x31\x29"}},
{IREP_TT_SSTR|(37<<2), {"\x6e\x65\x67\x61\x74\x69\x76\x65\x20\x61\x72\x72\x61\x79\x20\x73\x69\x7a\x65\x20\x28\x6f\x72\x20\x73\x69\x7a\x65\x20\x74\x6f\x6f\x20\x62\x69\x67\x29"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_2, 8, (MRB_SYM(begin), MRB_SYM(RangeError), MRB_SYM(raise), MRB_SYM_Q(empty), MRB_SYM(length), MRB_SYM(ArgumentError), MRB_SYM(__to_int), MRB_SYM(each), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_2[124] = {
0x39,0x00,0x10,0x00,0x30,0x06,0x00,0x29,0x06,0x00,0x03,0x26,0x00,0x0a,0x1d,0x07,0x01,0x5c,0x08,0x00,
0x2f,0x06,0x02,0x02,0x01,0x06,0x01,0x33,0x06,0x03,0x28,0x06,0x00,0x05,0x30,0x06,0x00,0x3d,0x06,0x01,
0x06,0x01,0x33,0x06,0x04,0x07,0x07,0x4d,0x06,0x27,0x06,0x00,0x17,0x1d,0x07,0x05,0x5c,0x08,0x01,0x01,
0x09,0x01,0x33,0x09,0x04,0x5d,0x08,0x5c,0x09,0x02,0x5d,0x08,0x2f,0x06,0x02,0x02,0x24,0x06,0x01,0x01,
0x03,0x06,0x01,0x06,0x03,0x33,0x06,0x06,0x01,0x04,0x06,0x06,0x06,0x01,0x07,0x04,0x4f,0x06,0x27,0x06,
0x00,0x0a,0x1d,0x07,0x05,0x5c,0x08,0x03,0x2f,0x06,0x02,0x02,0x52,0x05,0x00,0x62,0x07,0x00,0x31,0x06,
0x07,0x00,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_lv_2, 5, (MRB_SYM(args), 0,MRB_SYM(nv), MRB_SYM(n), MRB_SYM(ary), ), const);
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_2[] = "\x00\x0d\x04\x01\x14\x01\x0f\x02\x25\x01\x06\x01\x09\x01\x15\x01\x03\x01\x07\x05";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_2 = {
0, 278, 20, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_2}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_2_ = &gem_mrblib_mruby_range_ext_proc_debug_file_2;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_2 = {
124, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_2_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_2 = {
  6,11,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_2,
  gem_mrblib_mruby_range_ext_proc_pool_2,gem_mrblib_mruby_range_ext_proc_syms_2,gem_mrblib_mruby_range_ext_proc_reps_2,
  gem_mrblib_mruby_range_ext_proc_lv_2,
  &gem_mrblib_mruby_range_ext_proc_debug_2,
  124,4,8,1,0
};
static const mrb_irep_pool gem_mrblib_mruby_range_ext_proc_pool_3[4] = {
{IREP_TT_SSTR|(44<<2), {"\x63\x61\x6e\x6e\x6f\x74\x20\x67\x65\x74\x20\x74\x68\x65\x20\x6c\x61\x73\x74\x20\x65\x6c\x65\x6d\x65\x6e\x74\x20\x6f\x66\x20\x65\x6e\x64\x6c\x65\x73\x73\x20\x72\x61\x6e\x67\x65"}},
{IREP_TT_SSTR|(33<<2), {"\x77\x72\x6f\x6e\x67\x20\x6e\x75\x6d\x62\x65\x72\x20\x6f\x66\x20\x61\x72\x67\x75\x6d\x65\x6e\x74\x73\x20\x28\x67\x69\x76\x65\x6e\x20"}},
{IREP_TT_SSTR|(13<<2), {"\x2c\x20\x65\x78\x70\x65\x63\x74\x65\x64\x20\x31\x29"}},
{IREP_TT_SSTR|(37<<2), {"\x6e\x65\x67\x61\x74\x69\x76\x65\x20\x61\x72\x72\x61\x79\x20\x73\x69\x7a\x65\x20\x28\x6f\x72\x20\x73\x69\x7a\x65\x20\x74\x6f\x6f\x20\x62\x69\x67\x29"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_3, 9, (MRB_SYM(end), MRB_SYM(RangeError), MRB_SYM(raise), MRB_SYM_Q(empty), MRB_SYM(length), MRB_SYM(ArgumentError), MRB_SYM(__to_int), MRB_SYM(to_a), MRB_SYM(last), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_3[124] = {
0x39,0x00,0x10,0x00,0x30,0x05,0x00,0x29,0x05,0x00,0x03,0x26,0x00,0x0a,0x1d,0x06,0x01,0x5c,0x07,0x00,
0x2f,0x05,0x02,0x02,0x01,0x05,0x01,0x33,0x05,0x03,0x28,0x05,0x00,0x05,0x30,0x05,0x00,0x3d,0x05,0x01,
0x05,0x01,0x33,0x05,0x04,0x07,0x06,0x4d,0x05,0x27,0x05,0x00,0x17,0x1d,0x06,0x05,0x5c,0x07,0x01,0x01,
0x08,0x01,0x33,0x08,0x04,0x5d,0x07,0x5c,0x08,0x02,0x5d,0x07,0x2f,0x05,0x02,0x02,0x24,0x05,0x01,0x01,
0x03,0x05,0x01,0x05,0x03,0x33,0x05,0x06,0x01,0x04,0x05,0x06,0x05,0x01,0x06,0x04,0x4f,0x05,0x27,0x05,
0x00,0x0a,0x1d,0x06,0x05,0x5c,0x07,0x03,0x2f,0x05,0x02,0x02,0x30,0x05,0x07,0x01,0x06,0x03,0x32,0x05,
0x08,0x01,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_lv_3, 4, (MRB_SYM(args), 0,MRB_SYM(nv), MRB_SYM(n), ), const);
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_3[] = "\x00\x2d\x04\x01\x14\x01\x0f\x02\x25\x01\x06\x01\x09\x01\x15\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_3 = {
0, 278, 16, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_3}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_3_ = &gem_mrblib_mruby_range_ext_proc_debug_file_3;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_3 = {
124, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_3_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_3 = {
  5,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_3,
  gem_mrblib_mruby_range_ext_proc_pool_3,gem_mrblib_mruby_range_ext_proc_syms_3,NULL,
  gem_mrblib_mruby_range_ext_proc_lv_3,
  &gem_mrblib_mruby_range_ext_proc_debug_3,
  124,4,9,0,0
};
static const mrb_irep_pool gem_mrblib_mruby_range_ext_proc_pool_4[1] = {
{IREP_TT_SSTR|(39<<2), {"\x63\x61\x6e\x6e\x6f\x74\x20\x67\x65\x74\x20\x74\x68\x65\x20\x6d\x61\x78\x69\x6d\x75\x6d\x20\x6f\x66\x20\x65\x6e\x64\x6c\x65\x73\x73\x20\x72\x61\x6e\x67\x65"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_4, 10, (MRB_SYM(begin), MRB_SYM(end), MRB_SYM(RangeError), MRB_SYM(raise), MRB_SYM(Numeric), MRB_SYM_Q(kind_of), MRB_SYM_Q(exclude_end), MRB_SYM(Integer), MRB_OPSYM(not), MRB_SYM(TypeError), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_4[170] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x06,0x00,0x01,0x03,0x06,0x30,0x06,0x01,0x01,0x04,0x06,0x01,
0x06,0x02,0x28,0x06,0x00,0x08,0x01,0x07,0x02,0x37,0x06,0x00,0x3d,0x06,0x01,0x06,0x04,0x29,0x06,0x00,
0x03,0x26,0x00,0x0a,0x1d,0x07,0x02,0x5c,0x08,0x00,0x2f,0x06,0x03,0x02,0x01,0x06,0x03,0x1d,0x07,0x04,
0x32,0x06,0x05,0x01,0x28,0x06,0x00,0x0a,0x01,0x06,0x04,0x1d,0x07,0x04,0x32,0x06,0x05,0x01,0x28,0x06,
0x00,0x50,0x30,0x06,0x06,0x28,0x06,0x00,0x0d,0x01,0x06,0x04,0x1d,0x07,0x07,0x32,0x06,0x05,0x01,0x33,
0x06,0x08,0x28,0x06,0x00,0x07,0x1d,0x07,0x09,0x2f,0x06,0x03,0x01,0x01,0x06,0x03,0x01,0x07,0x04,0x50,
0x06,0x28,0x06,0x00,0x01,0x40,0x01,0x06,0x03,0x01,0x07,0x04,0x4d,0x06,0x28,0x06,0x00,0x03,0x30,0x06,
0x06,0x28,0x06,0x00,0x01,0x40,0x01,0x05,0x04,0x30,0x06,0x06,0x28,0x06,0x00,0x04,0x4a,0x05,0x06,0x01,
0x3d,0x05,0x01,0x07,0x01,0x37,0x06,0x00,0x3d,0x06,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_lv_4, 5, (0,MRB_SYM(block), MRB_SYM(val), MRB_SYM(last), MRB_SYM(max), ), const);
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_4[] = "\x00\x45\x07\x01\x06\x01\x06\x01\x0f\x02\x14\x03\x1a\x07\x02\xfa\xff\xff\xff\x0f\x1f\x01\x0d\x01\x14\x02\x03\x01\x0b\x01\x02\x04";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_4 = {
0, 278, 32, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_4}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_4_ = &gem_mrblib_mruby_range_ext_proc_debug_file_4;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_4 = {
170, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_4_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_4 = {
  6,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_4,
  gem_mrblib_mruby_range_ext_proc_pool_4,gem_mrblib_mruby_range_ext_proc_syms_4,NULL,
  gem_mrblib_mruby_range_ext_proc_lv_4,
  &gem_mrblib_mruby_range_ext_proc_debug_4,
  170,1,10,0,0
};
static const mrb_irep_pool gem_mrblib_mruby_range_ext_proc_pool_5[1] = {
{IREP_TT_SSTR|(69<<2), {"\x63\x61\x6e\x6e\x6f\x74\x20\x67\x65\x74\x20\x74\x68\x65\x20\x6d\x69\x6e\x69\x6d\x75\x6d\x20\x6f\x66\x20\x65\x6e\x64\x6c\x65\x73\x73\x20\x72\x61\x6e\x67\x65\x20\x77\x69\x74\x68\x20\x63\x75\x73\x74\x6f\x6d\x20\x63\x6f\x6d\x70\x61\x72\x69\x73\x6f\x6e\x20\x6d\x65\x74\x68\x6f\x64"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_5, 7, (MRB_SYM(begin), MRB_SYM(end), MRB_SYM(RangeError), MRB_SYM(raise), MRB_SYM(Numeric), MRB_SYM_Q(kind_of), MRB_SYM_Q(exclude_end), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_5[140] = {
0x39,0x00,0x00,0x01,0x01,0x02,0x01,0x30,0x06,0x00,0x01,0x03,0x06,0x30,0x06,0x01,0x01,0x04,0x06,0x01,
0x06,0x02,0x28,0x06,0x00,0x1c,0x01,0x06,0x04,0x29,0x06,0x00,0x03,0x26,0x00,0x0a,0x1d,0x07,0x02,0x5c,
0x08,0x00,0x2f,0x06,0x03,0x02,0x01,0x07,0x02,0x37,0x06,0x00,0x3d,0x06,0x01,0x06,0x04,0x29,0x06,0x00,
0x03,0x26,0x00,0x02,0x3d,0x03,0x01,0x06,0x03,0x1d,0x07,0x04,0x32,0x06,0x05,0x01,0x28,0x06,0x00,0x0a,
0x01,0x06,0x04,0x1d,0x07,0x04,0x32,0x06,0x05,0x01,0x28,0x06,0x00,0x26,0x01,0x06,0x03,0x01,0x07,0x04,
0x50,0x06,0x28,0x06,0x00,0x01,0x40,0x01,0x06,0x03,0x01,0x07,0x04,0x4d,0x06,0x28,0x06,0x00,0x03,0x30,
0x06,0x06,0x28,0x06,0x00,0x01,0x40,0x01,0x05,0x03,0x3d,0x05,0x01,0x07,0x01,0x37,0x06,0x00,0x3d,0x06,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_lv_5, 5, (0,MRB_SYM(block), MRB_SYM(val), MRB_SYM(last), MRB_SYM(min), ), const);
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_5[] = "\x00\x66\x07\x01\x06\x01\x06\x01\x05\x02\x02\xff\xff\xff\xff\x0f\x14\x01\x08\x02\x0c\x03\x1a\x05\x02\xfc\xff\xff\xff\x0f\x0d\x01\x14\x02\x03\x01\x02\x04";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_5 = {
0, 278, 38, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_5}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_5_ = &gem_mrblib_mruby_range_ext_proc_debug_file_5;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_5 = {
140, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_5_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_5 = {
  6,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_5,
  gem_mrblib_mruby_range_ext_proc_pool_5,gem_mrblib_mruby_range_ext_proc_syms_5,NULL,
  gem_mrblib_mruby_range_ext_proc_lv_5,
  &gem_mrblib_mruby_range_ext_proc_debug_5,
  140,1,7,0,0
};
static const mrb_irep_pool gem_mrblib_mruby_range_ext_proc_pool_6[1] = {
{IREP_TT_SSTR|(24<<2), {"\x61\x72\x67\x75\x6d\x65\x6e\x74\x20\x6d\x75\x73\x74\x20\x62\x65\x20\x61\x20\x72\x61\x6e\x67\x65"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_6, 8, (MRB_SYM(Range), MRB_SYM_Q(kind_of), MRB_SYM(TypeError), MRB_SYM(raise), MRB_SYM(begin), MRB_SYM(end), MRB_SYM_Q(exclude_end), MRB_SYM_Q(__empty_range), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_6[159] = {
0x39,0x04,0x00,0x00,0x01,0x09,0x01,0x1d,0x0a,0x00,0x32,0x09,0x01,0x01,0x27,0x09,0x00,0x0a,0x1d,0x0a,
0x02,0x5c,0x0b,0x00,0x2f,0x09,0x03,0x02,0x30,0x09,0x04,0x01,0x03,0x09,0x01,0x09,0x01,0x33,0x09,0x05,
0x01,0x04,0x09,0x01,0x09,0x01,0x33,0x09,0x06,0x01,0x05,0x09,0x01,0x0a,0x03,0x01,0x0b,0x04,0x01,0x0c,
0x05,0x2f,0x09,0x07,0x03,0x28,0x09,0x00,0x01,0x42,0x01,0x09,0x01,0x33,0x09,0x04,0x01,0x06,0x09,0x30,
0x09,0x05,0x01,0x07,0x09,0x30,0x09,0x06,0x01,0x08,0x09,0x01,0x0a,0x06,0x01,0x0b,0x07,0x01,0x0c,0x08,
0x2f,0x09,0x07,0x03,0x28,0x09,0x00,0x01,0x42,0x01,0x09,0x03,0x01,0x0a,0x06,0x4d,0x09,0x28,0x09,0x00,
0x01,0x41,0x01,0x0a,0x03,0x01,0x0b,0x07,0x01,0x0c,0x08,0x2f,0x09,0x07,0x03,0x28,0x09,0x00,0x01,0x42,
0x01,0x0a,0x06,0x01,0x0b,0x04,0x01,0x0c,0x05,0x2f,0x09,0x07,0x03,0x28,0x09,0x00,0x01,0x42,0x41,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_lv_6, 8, (MRB_SYM(other), 0,MRB_SYM(self_begin), MRB_SYM(other_end), MRB_SYM(other_excl), MRB_SYM(other_begin), MRB_SYM(self_end), MRB_SYM(self_excl), ), const);
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_6[] = "\x00\x86\x01\x04\x01\x18\x02\x06\x01\x09\x01\x09\x02\x12\x02\x09\x01\x06\x01\x06\x02\x12\x01\x0d\x02\x12\x01\x12\x02";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_6 = {
0, 278, 29, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_6}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_6_ = &gem_mrblib_mruby_range_ext_proc_debug_file_6;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_6 = {
159, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_6_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_6 = {
  9,14,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_6,
  gem_mrblib_mruby_range_ext_proc_pool_6,gem_mrblib_mruby_range_ext_proc_syms_6,NULL,
  gem_mrblib_mruby_range_ext_proc_lv_6,
  &gem_mrblib_mruby_range_ext_proc_debug_6,
  159,1,8,0,0
};
static const mrb_irep *gem_mrblib_mruby_range_ext_proc_reps_1[5] = {
  &gem_mrblib_mruby_range_ext_proc_irep_2,
  &gem_mrblib_mruby_range_ext_proc_irep_3,
  &gem_mrblib_mruby_range_ext_proc_irep_4,
  &gem_mrblib_mruby_range_ext_proc_irep_5,
  &gem_mrblib_mruby_range_ext_proc_irep_6,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_1, 5, (MRB_SYM(first), MRB_SYM(last), MRB_SYM(max), MRB_SYM(min), MRB_SYM_Q(overlap), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_1[22] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x3d,0x01,};
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_1[] = "\x00\x0d\x04\x20\x04\x18\x04\x21\x04\x20";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_1 = {
0, 278, 10, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_1}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_1_ = &gem_mrblib_mruby_range_ext_proc_debug_file_1;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_1 = {
22, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_1_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_1 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_1,
  NULL,gem_mrblib_mruby_range_ext_proc_syms_1,gem_mrblib_mruby_range_ext_proc_reps_1,
  NULL,					/* lv */
  &gem_mrblib_mruby_range_ext_proc_debug_1,
  22,0,5,5,0
};
static const mrb_irep *gem_mrblib_mruby_range_ext_proc_reps_0[1] = {
  &gem_mrblib_mruby_range_ext_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_range_ext_proc_syms_0, 1, (MRB_SYM(Range), ), const);
static const mrb_code gem_mrblib_mruby_range_ext_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const char gem_mrblib_mruby_range_ext_proc_debug_lines_0[] = "\x00\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_range_ext_proc_debug_file_0 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_range_ext_proc_debug_lines_0}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_range_ext_proc_debug_file_0_ = &gem_mrblib_mruby_range_ext_proc_debug_file_0;
static mrb_irep_debug_info gem_mrblib_mruby_range_ext_proc_debug_0 = {
13, 1, &gem_mrblib_mruby_range_ext_proc_debug_file_0_};
static const mrb_irep gem_mrblib_mruby_range_ext_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_range_ext_proc_iseq_0,
  NULL,gem_mrblib_mruby_range_ext_proc_syms_0,gem_mrblib_mruby_range_ext_proc_reps_0,
  NULL,					/* lv */
  &gem_mrblib_mruby_range_ext_proc_debug_0,
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_range_ext_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_range_ext_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_range_ext_proc_init_syms(mrb_state *mrb)
{
  gem_mrblib_mruby_range_ext_proc_debug_file_7.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_2.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_3.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_4.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_5.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_6.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_1.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
  gem_mrblib_mruby_range_ext_proc_debug_file_0.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-range-ext/mrblib/range.rb");
}
void mrb_mruby_range_ext_gem_init(mrb_state *mrb);
void mrb_mruby_range_ext_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_range_ext_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_range_ext_proc_init_syms(mrb);
  mrb_mruby_range_ext_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_range_ext_proc);
}

void GENERATED_TMP_mrb_mruby_range_ext_gem_final(mrb_state *mrb) {
  mrb_mruby_range_ext_gem_final(mrb);
}
