/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>
#include <mruby/presym.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_2, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_2[17] = {
0x39,0x00,0x10,0x00,0x11,0x04,0x01,0x05,0x01,0x54,0x04,0x2f,0x03,0x00,0x0f,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_2, 2, (MRB_SYM(args), 0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_2[] = "\x00\x17\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_2 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_2}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_2_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_2;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_2 = {
17, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_2_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_2 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_2,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_2,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_2,
  &gem_mrblib_mruby_proc_ext_proc_debug_2,
  17,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_3, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_3[17] = {
0x39,0x00,0x10,0x00,0x11,0x04,0x01,0x05,0x01,0x54,0x04,0x2f,0x03,0x00,0x0f,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_3, 2, (MRB_SYM(args), 0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_3[] = "\x00\x25\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_3 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_3}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_3_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_3;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_3 = {
17, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_3_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_3 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_3,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_3,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_3,
  &gem_mrblib_mruby_proc_ext_proc_debug_3,
  17,0,1,0,0
};
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_4[5] = {
0x39,0x00,0x00,0x00,0x3f,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_4, 1, (0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_4[] = "\x00\x33\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_4 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_4}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_4_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_4;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_4 = {
5, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_4_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_4 = {
  2,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_4,
  NULL,NULL,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_4,
  &gem_mrblib_mruby_proc_ext_proc_debug_4,
  5,0,0,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_26, 1, (MRB_OPSYM(minus), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_26[33] = {
0x39,0x04,0x00,0x00,0x01,0x03,0x01,0x06,0x04,0x4e,0x03,0x28,0x03,0x00,0x0d,0x01,0x03,0x01,0x32,0x03,
0x00,0x00,0x48,0x03,0x01,0x26,0x00,0x03,0x01,0x03,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_26, 2, (MRB_SYM(a), 0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_26[] = "\x00\x49";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_26 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_26}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_26_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_26;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_26 = {
33, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_26_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_26 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_26,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_26,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_26,
  &gem_mrblib_mruby_proc_ext_proc_debug_26,
  33,0,1,0,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_30, 2, (MRB_SYM(size), MRB_OPSYM(aref), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_30[61] = {
0x39,0x00,0x10,0x00,0x21,0x04,0x01,0x00,0x01,0x05,0x01,0x45,0x04,0x01,0x03,0x04,0x01,0x04,0x03,0x33,
0x04,0x00,0x21,0x05,0x01,0x01,0x51,0x04,0x28,0x04,0x00,0x12,0x21,0x04,0x06,0x01,0x11,0x05,0x01,0x06,
0x03,0x54,0x05,0x32,0x04,0x01,0x0f,0x26,0x00,0x09,0x21,0x04,0x07,0x01,0x01,0x05,0x03,0x23,0x04,0x3d,
0x04,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_30, 3, (MRB_SYM(args), 0,MRB_SYM(new_args), ), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_30[] = "\x00\x56\x04\x01\x0c\x01\x0e\x01\x12\x02";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_30 = {
0, 278, 10, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_30}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_30_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_30;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_30 = {
61, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_30_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_30 = {
  4,7,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_30,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_30,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_30,
  &gem_mrblib_mruby_proc_ext_proc_debug_30,
  61,0,2,0,0
};
static const mrb_irep *gem_mrblib_mruby_proc_ext_proc_reps_27[1] = {
  &gem_mrblib_mruby_proc_ext_proc_irep_30,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_27, 1, (MRB_SYM(__send__), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_27[26] = {
0x39,0x00,0x20,0x00,0x26,0x00,0x03,0x26,0x00,0x03,0x52,0x01,0x00,0x21,0x04,0x03,0x00,0x62,0x05,0x00,
0x31,0x03,0x00,0x01,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_27, 2, (MRB_SYM(given_args), 0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_27[] = "\x00\x55\x0d\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_27 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_27}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_27_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_27;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_27 = {
26, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_27_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_27 = {
  3,6,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_27,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_27,gem_mrblib_mruby_proc_ext_proc_reps_27,
  gem_mrblib_mruby_proc_ext_proc_lv_27,
  &gem_mrblib_mruby_proc_ext_proc_debug_27,
  26,0,1,1,0
};
static const mrb_irep *gem_mrblib_mruby_proc_ext_proc_reps_5[2] = {
  &gem_mrblib_mruby_proc_ext_proc_irep_26,
  &gem_mrblib_mruby_proc_ext_proc_irep_27,
};
static const mrb_irep_pool gem_mrblib_mruby_proc_ext_proc_pool_5[3] = {
{IREP_TT_SSTR|(33<<2), {"\x77\x72\x6f\x6e\x67\x20\x6e\x75\x6d\x62\x65\x72\x20\x6f\x66\x20\x61\x72\x67\x75\x6d\x65\x6e\x74\x73\x20\x28\x67\x69\x76\x65\x6e\x20"}},
{IREP_TT_SSTR|(11<<2), {"\x2c\x20\x65\x78\x70\x65\x63\x74\x65\x64\x20"}},
{IREP_TT_SSTR|(1<<2), {"\x29"}},
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_5, 8, (MRB_SYM(arity), MRB_SYM(proc), MRB_SYM(lambda), MRB_SYM_Q(lambda), MRB_OPSYM(neq), MRB_SYM(ArgumentError), MRB_SYM(raise), MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_5[164] = {
0x39,0x00,0x20,0x00,0x26,0x00,0x03,0x26,0x00,0x06,0x30,0x08,0x00,0x01,0x01,0x08,0x10,0x03,0x01,0x62,
0x09,0x00,0x31,0x08,0x02,0x00,0x01,0x04,0x08,0x01,0x08,0x04,0x01,0x09,0x01,0x23,0x08,0x01,0x01,0x08,
0x30,0x08,0x03,0x28,0x08,0x00,0x61,0x10,0x03,0x02,0x30,0x08,0x00,0x01,0x05,0x08,0x01,0x08,0x05,0x06,
0x09,0x51,0x08,0x28,0x08,0x00,0x0a,0x01,0x08,0x01,0x01,0x09,0x05,0x32,0x08,0x04,0x01,0x27,0x08,0x00,
0x18,0x01,0x08,0x05,0x06,0x09,0x4e,0x08,0x28,0x08,0x00,0x0d,0x01,0x08,0x04,0x01,0x09,0x05,0x23,0x08,
0x01,0x09,0x01,0x50,0x08,0x28,0x08,0x00,0x23,0x1d,0x09,0x05,0x5c,0x0a,0x00,0x01,0x0b,0x01,0x5d,0x0a,
0x5c,0x0b,0x01,0x5d,0x0a,0x01,0x0b,0x04,0x01,0x0c,0x05,0x23,0x0b,0x5d,0x0a,0x5c,0x0b,0x02,0x5d,0x0a,
0x2f,0x08,0x06,0x02,0x12,0x06,0x62,0x09,0x01,0x31,0x08,0x01,0x00,0x01,0x07,0x08,0x01,0x08,0x07,0x33,
0x08,0x07,0x3d,0x08,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_5, 7, (MRB_SYM(arity), 0,MRB_SYM(type), MRB_SYM(abs), MRB_SYM(self_arity), MRB_SYM(pproc), MRB_SYM(make_curry), ), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_5[] = "\x00\x47\x10\x01\x03\x01\x0a\x01\x0b\x01\x05\x05\x02\xfc\xff\xff\xff\x0f\x03\x01\x06\x01\x17\x01\x1c\x01\x25\x04\x02\x01\x0a\x0a";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_5 = {
0, 278, 32, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_5}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_5_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_5;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_5 = {
164, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_5_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_5 = {
  8,14,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_5,
  gem_mrblib_mruby_proc_ext_proc_pool_5,gem_mrblib_mruby_proc_ext_proc_syms_5,gem_mrblib_mruby_proc_ext_proc_reps_5,
  gem_mrblib_mruby_proc_ext_proc_lv_5,
  &gem_mrblib_mruby_proc_ext_proc_debug_5,
  164,3,8,2,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_37, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_37[39] = {
0x39,0x00,0x10,0x03,0x01,0x04,0x03,0x21,0x06,0x01,0x00,0x11,0x07,0x01,0x08,0x01,0x54,0x07,0x5e,0x08,
0x00,0x01,0x09,0x02,0x60,0x08,0x01,0x09,0x04,0x34,0x06,0x00,0xff,0x2f,0x05,0x00,0x01,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_37, 4, (MRB_SYM(args), MRB_SYM(opts), 0,MRB_SYM(block), ), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_37[] = "\x00\x6f";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_37 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_37}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_37_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_37;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_37 = {
39, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_37_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_37 = {
  5,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_37,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_37,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_37,
  &gem_mrblib_mruby_proc_ext_proc_debug_37,
  39,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_proc_ext_proc_reps_6[1] = {
  &gem_mrblib_mruby_proc_ext_proc_irep_37,
};
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_6[9] = {
0x39,0x04,0x00,0x00,0x61,0x03,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_6, 2, (MRB_SYM(other), 0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_6[] = "\x00\x6e\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_6 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_6}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_6_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_6;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_6 = {
9, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_6_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_6 = {
  3,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_6,
  NULL,NULL,gem_mrblib_mruby_proc_ext_proc_reps_6,
  gem_mrblib_mruby_proc_ext_proc_lv_6,
  &gem_mrblib_mruby_proc_ext_proc_debug_6,
  9,0,0,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_44, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_44[39] = {
0x39,0x00,0x10,0x03,0x01,0x04,0x03,0x21,0x05,0x01,0x00,0x11,0x07,0x01,0x08,0x01,0x54,0x07,0x5e,0x08,
0x00,0x01,0x09,0x02,0x60,0x08,0x01,0x09,0x04,0x31,0x06,0x00,0xff,0x32,0x05,0x00,0x01,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_44, 4, (MRB_SYM(args), MRB_SYM(opts), 0,MRB_SYM(block), ), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_44[] = "\x00\x7f";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_44 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_44}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_44_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_44;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_44 = {
39, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_44_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_44 = {
  5,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_44,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_44,NULL,
  gem_mrblib_mruby_proc_ext_proc_lv_44,
  &gem_mrblib_mruby_proc_ext_proc_debug_44,
  39,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_proc_ext_proc_reps_7[1] = {
  &gem_mrblib_mruby_proc_ext_proc_irep_44,
};
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_7[9] = {
0x39,0x04,0x00,0x00,0x61,0x03,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_lv_7, 2, (MRB_SYM(other), 0,), const);
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_7[] = "\x00\x7e\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_7 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_7}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_7_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_7;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_7 = {
9, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_7_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_7 = {
  3,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_7,
  NULL,NULL,gem_mrblib_mruby_proc_ext_proc_reps_7,
  gem_mrblib_mruby_proc_ext_proc_lv_7,
  &gem_mrblib_mruby_proc_ext_proc_debug_7,
  9,0,0,1,0
};
static const mrb_irep *gem_mrblib_mruby_proc_ext_proc_reps_1[6] = {
  &gem_mrblib_mruby_proc_ext_proc_irep_2,
  &gem_mrblib_mruby_proc_ext_proc_irep_3,
  &gem_mrblib_mruby_proc_ext_proc_irep_4,
  &gem_mrblib_mruby_proc_ext_proc_irep_5,
  &gem_mrblib_mruby_proc_ext_proc_irep_6,
  &gem_mrblib_mruby_proc_ext_proc_irep_7,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_1, 6, (MRB_OPSYM(eqq), MRB_SYM(yield), MRB_SYM(to_proc), MRB_SYM(curry), MRB_OPSYM(lshift), MRB_OPSYM(rshift), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_1[26] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x6b,0x01,0x03,0x03,0x6b,0x01,0x04,0x04,
0x6b,0x01,0x05,0x05,0x3d,0x01,};
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_1[] = "\x00\x17\x04\x0e\x04\x0e\x04\x14\x04\x27\x04\x10";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_1 = {
0, 278, 12, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_1}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_1_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_1;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_1 = {
26, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_1_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_1 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_1,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_1,gem_mrblib_mruby_proc_ext_proc_reps_1,
  NULL,					/* lv */
  &gem_mrblib_mruby_proc_ext_proc_debug_1,
  26,0,6,6,0
};
static const mrb_irep *gem_mrblib_mruby_proc_ext_proc_reps_0[1] = {
  &gem_mrblib_mruby_proc_ext_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_proc_ext_proc_syms_0, 1, (MRB_SYM(Proc), ), const);
static const mrb_code gem_mrblib_mruby_proc_ext_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const char gem_mrblib_mruby_proc_ext_proc_debug_lines_0[] = "\x00\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_proc_ext_proc_debug_file_0 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_proc_ext_proc_debug_lines_0}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_proc_ext_proc_debug_file_0_ = &gem_mrblib_mruby_proc_ext_proc_debug_file_0;
static mrb_irep_debug_info gem_mrblib_mruby_proc_ext_proc_debug_0 = {
13, 1, &gem_mrblib_mruby_proc_ext_proc_debug_file_0_};
static const mrb_irep gem_mrblib_mruby_proc_ext_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_proc_ext_proc_iseq_0,
  NULL,gem_mrblib_mruby_proc_ext_proc_syms_0,gem_mrblib_mruby_proc_ext_proc_reps_0,
  NULL,					/* lv */
  &gem_mrblib_mruby_proc_ext_proc_debug_0,
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_proc_ext_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_proc_ext_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_proc_ext_proc_init_syms(mrb_state *mrb)
{
  gem_mrblib_mruby_proc_ext_proc_debug_file_2.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_3.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_4.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_26.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_30.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_27.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_5.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_37.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_6.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_44.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_7.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_1.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
  gem_mrblib_mruby_proc_ext_proc_debug_file_0.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-proc-ext/mrblib/proc.rb");
}
void mrb_mruby_proc_ext_gem_init(mrb_state *mrb);
void mrb_mruby_proc_ext_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_proc_ext_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_proc_ext_proc_init_syms(mrb);
  mrb_mruby_proc_ext_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_proc_ext_proc);
}

void GENERATED_TMP_mrb_mruby_proc_ext_gem_final(mrb_state *mrb) {
  mrb_mruby_proc_ext_gem_final(mrb);
}
