# frozen_string_literal: true

module RubyNative
  module UI
    module MaterialControlRegistry
      TYPE_MAP = {
        "text" => "Text",
        "column" => "Column",
        "row" => "Row",
        "stack" => "Stack",
        "view" => "View",
        "container" => "Container",
        "checkbox" => "Checkbox",
        "radio" => "Radio",
        "radiogroup" => "RadioGroup",
        "radio_group" => "RadioGroup",
        "alertdialog" => "AlertDialog",
        "alert_dialog" => "AlertDialog",
        "snackbar" => "SnackBar",
        "snack_bar" => "SnackBar",
        "bottomsheet" => "BottomSheet",
        "bottom_sheet" => "BottomSheet",
        "markdown" => "Markdown",
        "textbutton" => "TextButton",
        "text_button" => "TextButton",
        "filledbutton" => "FilledButton",
        "filled_button" => "FilledButton",
        "gesturedetector" => "GestureDetector",
        "gesture_detector" => "GestureDetector",
        "draggable" => "Draggable",
        "dragtarget" => "DragTarget",
        "drag_target" => "DragTarget",
        "textfield" => "TextField",
        "text_field" => "TextField",
        "button" => "Button",
        "elevatedbutton" => "Button",
        "elevated_button" => "Button",
        "iconbutton" => "IconButton",
        "icon_button" => "IconButton",
        "icon" => "Icon",
        "image" => "Image",
        "appbar" => "AppBar",
        "app_bar" => "AppBar",
        "floatingactionbutton" => "FloatingActionButton",
        "floating_action_button" => "FloatingActionButton",
        "tabs" => "Tabs",
        "tab" => "Tab",
        "tabbar" => "TabBar",
        "tab_bar" => "TabBar",
        "tabbarview" => "TabBarView",
        "tab_bar_view" => "TabBarView",
        "navigationbar" => "NavigationBar",
        "navigation_bar" => "NavigationBar",
        "navigationbardestination" => "NavigationBarDestination",
        "navigation_bar_destination" => "NavigationBarDestination"
      }.freeze

      EVENT_PROPS = {
        on_click: "click",
        on_change: "change",
        on_action: "action",
        on_submit: "submit",
        on_dismiss: "dismiss",
        on_tap: "tap",
        on_double_tap: "double_tap",
        on_long_press: "long_press",
        on_hover: "hover",
        on_pan_start: "pan_start",
        on_pan_update: "pan_update",
        on_pan_end: "pan_end",
        on_scale_start: "scale_start",
        on_scale_update: "scale_update",
        on_scale_end: "scale_end",
        on_vertical_drag_start: "vertical_drag_start",
        on_vertical_drag_update: "vertical_drag_update",
        on_vertical_drag_end: "vertical_drag_end",
        on_horizontal_drag_start: "horizontal_drag_start",
        on_horizontal_drag_update: "horizontal_drag_update",
        on_horizontal_drag_end: "horizontal_drag_end",
        on_accept: "accept",
        on_will_accept: "will_accept",
        on_accept_with_details: "accept_with_details",
        on_move: "move",
        on_leave: "leave"
      }.freeze
    end
  end
end
