/*
 * This file is loading the irep
 * Ruby GEM code.
 *
 * This file was generated by mruby/lib/mruby/gem.rb.
 *
 * IMPORTANT:
 *   This file was generated!
 *   All manual changes will get lost.
 */
#include <stdlib.h>
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/debug.h>
#include <mruby/proc.h>
#include <mruby/presym.h>

#define mrb_BRACED(...) {__VA_ARGS__}
#define mrb_DEFINE_SYMS_VAR(name, len, syms, qualifier) \
  static qualifier mrb_sym name[len] = mrb_BRACED syms

mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_syms_5, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_method_proc_iseq_5[35] = {
0x39,0x00,0x10,0x03,0x01,0x04,0x03,0x21,0x05,0x02,0x00,0x11,0x06,0x01,0x07,0x01,0x54,0x06,0x5e,0x07,
0x00,0x01,0x08,0x02,0x60,0x07,0x01,0x08,0x04,0x34,0x05,0x00,0xff,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_lv_5, 4, (MRB_SYM(args), MRB_SYM(opts), 0,MRB_SYM(b), ), const);
static const char gem_mrblib_mruby_method_proc_debug_lines_5[] = "\x00\x17\x07\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_5 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_5}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_5_ = &gem_mrblib_mruby_method_proc_debug_file_5;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_5 = {
35, 1, &gem_mrblib_mruby_method_proc_debug_file_5_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_5 = {
  5,9,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_5,
  NULL,gem_mrblib_mruby_method_proc_syms_5,NULL,
  gem_mrblib_mruby_method_proc_lv_5,
  &gem_mrblib_mruby_method_proc_debug_5,
  35,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_method_proc_reps_2[1] = {
  &gem_mrblib_mruby_method_proc_irep_5,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_syms_2, 1, (MRB_SYM(lambda), ), const);
static const mrb_code gem_mrblib_mruby_method_proc_iseq_2[15] = {
0x39,0x00,0x00,0x00,0x12,0x02,0x62,0x04,0x00,0x31,0x03,0x00,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_lv_2, 2, (0,MRB_SYM(m), ), const);
static const char gem_mrblib_mruby_method_proc_debug_lines_2[] = "\x00\x15\x04\x01\x02\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_2 = {
0, 278, 6, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_2}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_2_ = &gem_mrblib_mruby_method_proc_debug_file_2;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_2 = {
15, 1, &gem_mrblib_mruby_method_proc_debug_file_2_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_2 = {
  3,5,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_2,
  NULL,gem_mrblib_mruby_method_proc_syms_2,gem_mrblib_mruby_method_proc_reps_2,
  gem_mrblib_mruby_method_proc_lv_2,
  &gem_mrblib_mruby_method_proc_debug_2,
  15,0,1,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_syms_9, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_method_proc_iseq_9[39] = {
0x39,0x00,0x10,0x03,0x01,0x04,0x03,0x21,0x06,0x01,0x00,0x11,0x07,0x01,0x08,0x01,0x54,0x07,0x5e,0x08,
0x00,0x01,0x09,0x02,0x60,0x08,0x01,0x09,0x04,0x34,0x06,0x00,0xff,0x2f,0x05,0x00,0x01,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_lv_9, 4, (MRB_SYM(args), MRB_SYM(opts), 0,MRB_SYM(block), ), const);
static const char gem_mrblib_mruby_method_proc_debug_lines_9[] = "\x00\x30";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_9 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_9}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_9_ = &gem_mrblib_mruby_method_proc_debug_file_9;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_9 = {
39, 1, &gem_mrblib_mruby_method_proc_debug_file_9_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_9 = {
  5,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_9,
  NULL,gem_mrblib_mruby_method_proc_syms_9,NULL,
  gem_mrblib_mruby_method_proc_lv_9,
  &gem_mrblib_mruby_method_proc_debug_9,
  39,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_method_proc_reps_3[1] = {
  &gem_mrblib_mruby_method_proc_irep_9,
};
static const mrb_code gem_mrblib_mruby_method_proc_iseq_3[9] = {
0x39,0x04,0x00,0x00,0x61,0x03,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_lv_3, 2, (MRB_SYM(other), 0,), const);
static const char gem_mrblib_mruby_method_proc_debug_lines_3[] = "\x00\x2f\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_3 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_3}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_3_ = &gem_mrblib_mruby_method_proc_debug_file_3;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_3 = {
9, 1, &gem_mrblib_mruby_method_proc_debug_file_3_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_3 = {
  3,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_3,
  NULL,NULL,gem_mrblib_mruby_method_proc_reps_3,
  gem_mrblib_mruby_method_proc_lv_3,
  &gem_mrblib_mruby_method_proc_debug_3,
  9,0,0,1,0
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_syms_13, 1, (MRB_SYM(call), ), const);
static const mrb_code gem_mrblib_mruby_method_proc_iseq_13[39] = {
0x39,0x00,0x10,0x03,0x01,0x04,0x03,0x21,0x05,0x01,0x00,0x11,0x07,0x01,0x08,0x01,0x54,0x07,0x5e,0x08,
0x00,0x01,0x09,0x02,0x60,0x08,0x01,0x09,0x04,0x31,0x06,0x00,0xff,0x32,0x05,0x00,0x01,0x3d,0x05,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_lv_13, 4, (MRB_SYM(args), MRB_SYM(opts), 0,MRB_SYM(block), ), const);
static const char gem_mrblib_mruby_method_proc_debug_lines_13[] = "\x00\x47";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_13 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_13}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_13_ = &gem_mrblib_mruby_method_proc_debug_file_13;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_13 = {
39, 1, &gem_mrblib_mruby_method_proc_debug_file_13_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_13 = {
  5,10,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_13,
  NULL,gem_mrblib_mruby_method_proc_syms_13,NULL,
  gem_mrblib_mruby_method_proc_lv_13,
  &gem_mrblib_mruby_method_proc_debug_13,
  39,0,1,0,0
};
static const mrb_irep *gem_mrblib_mruby_method_proc_reps_4[1] = {
  &gem_mrblib_mruby_method_proc_irep_13,
};
static const mrb_code gem_mrblib_mruby_method_proc_iseq_4[9] = {
0x39,0x04,0x00,0x00,0x61,0x03,0x00,0x3d,0x03,};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_lv_4, 2, (MRB_SYM(other), 0,), const);
static const char gem_mrblib_mruby_method_proc_debug_lines_4[] = "\x00\x46\x04\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_4 = {
0, 278, 4, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_4}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_4_ = &gem_mrblib_mruby_method_proc_debug_file_4;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_4 = {
9, 1, &gem_mrblib_mruby_method_proc_debug_file_4_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_4 = {
  3,4,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_4,
  NULL,NULL,gem_mrblib_mruby_method_proc_reps_4,
  gem_mrblib_mruby_method_proc_lv_4,
  &gem_mrblib_mruby_method_proc_debug_4,
  9,0,0,1,0
};
static const mrb_irep *gem_mrblib_mruby_method_proc_reps_1[3] = {
  &gem_mrblib_mruby_method_proc_irep_2,
  &gem_mrblib_mruby_method_proc_irep_3,
  &gem_mrblib_mruby_method_proc_irep_4,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_syms_1, 3, (MRB_SYM(to_proc), MRB_OPSYM(lshift), MRB_OPSYM(rshift), ), const);
static const mrb_code gem_mrblib_mruby_method_proc_iseq_1[14] = {
0x6b,0x01,0x00,0x00,0x6b,0x01,0x01,0x01,0x6b,0x01,0x02,0x02,0x3d,0x01,};
static const char gem_mrblib_mruby_method_proc_debug_lines_1[] = "\x00\x15\x04\x1a\x04\x17";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_1 = {
0, 278, 6, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_1}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_1_ = &gem_mrblib_mruby_method_proc_debug_file_1;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_1 = {
14, 1, &gem_mrblib_mruby_method_proc_debug_file_1_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_1 = {
  1,2,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_1,
  NULL,gem_mrblib_mruby_method_proc_syms_1,gem_mrblib_mruby_method_proc_reps_1,
  NULL,					/* lv */
  &gem_mrblib_mruby_method_proc_debug_1,
  14,0,3,3,0
};
static const mrb_irep *gem_mrblib_mruby_method_proc_reps_0[1] = {
  &gem_mrblib_mruby_method_proc_irep_1,
};
mrb_DEFINE_SYMS_VAR(gem_mrblib_mruby_method_proc_syms_0, 1, (MRB_SYM(Method), ), const);
static const mrb_code gem_mrblib_mruby_method_proc_iseq_0[13] = {
0x11,0x01,0x11,0x02,0x67,0x01,0x00,0x69,0x01,0x00,0x3d,0x01,0x76,};
static const char gem_mrblib_mruby_method_proc_debug_lines_0[] = "\x00\x01";
static mrb_irep_debug_info_file gem_mrblib_mruby_method_proc_debug_file_0 = {
0, 278, 2, mrb_debug_line_packed_map, {gem_mrblib_mruby_method_proc_debug_lines_0}};
static mrb_irep_debug_info_file *gem_mrblib_mruby_method_proc_debug_file_0_ = &gem_mrblib_mruby_method_proc_debug_file_0;
static mrb_irep_debug_info gem_mrblib_mruby_method_proc_debug_0 = {
13, 1, &gem_mrblib_mruby_method_proc_debug_file_0_};
static const mrb_irep gem_mrblib_mruby_method_proc_irep_0 = {
  1,3,0,
  MRB_IREP_STATIC,gem_mrblib_mruby_method_proc_iseq_0,
  NULL,gem_mrblib_mruby_method_proc_syms_0,gem_mrblib_mruby_method_proc_reps_0,
  NULL,					/* lv */
  &gem_mrblib_mruby_method_proc_debug_0,
  13,0,1,1,0
};
static
const struct RProc gem_mrblib_mruby_method_proc[] = {{
NULL,MRB_TT_PROC,MRB_GC_RED,MRB_OBJ_IS_FROZEN,0,{&gem_mrblib_mruby_method_proc_irep_0},NULL,{NULL},
}};
static void
gem_mrblib_mruby_method_proc_init_syms(mrb_state *mrb)
{
  gem_mrblib_mruby_method_proc_debug_file_5.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_2.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_9.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_3.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_13.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_4.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_1.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
  gem_mrblib_mruby_method_proc_debug_file_0.filename_sym = mrb_intern_lit(mrb,"/Users/macbookpro/Documents/Izeesoft/FlutterApp/ruflet/ruby_runtime/third_party/mruby/mrbgems/mruby-method/mrblib/method.rb");
}
void mrb_mruby_method_gem_init(mrb_state *mrb);
void mrb_mruby_method_gem_final(mrb_state *mrb);

void GENERATED_TMP_mrb_mruby_method_gem_init(mrb_state *mrb) {
  gem_mrblib_mruby_method_proc_init_syms(mrb);
  mrb_mruby_method_gem_init(mrb);
  mrb_load_proc(mrb, gem_mrblib_mruby_method_proc);
}

void GENERATED_TMP_mrb_mruby_method_gem_final(mrb_state *mrb) {
  mrb_mruby_method_gem_final(mrb);
}
