#!/usr/bin/env ruby
# frozen_string_literal: true

# Syncs the device VMs' mruby gem set from the vendored mruby tree.
#
# The device VM must expose the same Ruby surface as the host_vm test build
# (ruby_runtime/vm/build_config/host_vm.rb): full core stdlib + IO/socket/dir
# + Regexp + Digest. This script copies each gem's C sources/headers from
# third_party/mruby and the generated gem_init.c (ruby-part bytecode) from
# the host_vm build output into every platform plugin, and regenerates
# mruby_gems_init.c.
#
# Run after building the host_vm target:
#   cd ruby_runtime/third_party/mruby
#   rake MRUBY_CONFIG=../../vm/build_config/host_vm.rb
#   ruby ../../tools/sync_device_mruby_gems.rb

require "fileutils"
require "pathname"

ROOT = Pathname(__dir__).join("..").expand_path
MRUBY = ROOT.join("ruby_runtime/third_party/mruby")
HOST_VM_BUILD = MRUBY.join("build/host_vm")

# Init order: HALs and primitives first, then gems in dependency order
# (fiber before enumerator, enumerator before the enum-* family, io before
# dir/socket), extensions last.
CORE_GEMS = %w[
  mruby-error
  mruby-errno
  mruby-array-ext
  mruby-string-ext
  mruby-hash-ext
  mruby-object-ext
  mruby-kernel-ext
  mruby-symbol-ext
  mruby-proc-ext
  mruby-binding
  mruby-proc-binding
  mruby-eval
  mruby-class-ext
  mruby-compar-ext
  mruby-range-ext
  mruby-numeric-ext
  mruby-toplevel-ext
  mruby-metaprog
  mruby-method
  mruby-data
  mruby-struct
  mruby-set
  mruby-fiber
  mruby-enumerator
  mruby-enum-ext
  mruby-enum-lazy
  mruby-enum-chain
  mruby-math
  mruby-random
  mruby-sprintf
  mruby-pack
  mruby-time
  mruby-sleep
  mruby-catch
  mruby-encoding
  mruby-io
  mruby-dir
  mruby-socket
].freeze

CORE_SOURCE_GEMS = %w[mruby-bigint].freeze

PRELOADED_RUBY_GEMS = %w[ruflet-framework].freeze
NATIVE_RUBY_GEMS = %w[mruby-onig-regexp ruflet-record].freeze

HAL_GEMS = %w[hal-posix-io hal-posix-socket hal-posix-dir].freeze

PLATFORM_TARGETS = {
  "macos" => ROOT.join("ruby_runtime/macos/mruby_src"),
  "ios" => ROOT.join("ruby_runtime/ios/mruby_src")
}.freeze

def gem_init_symbol(gem_name)
  "GENERATED_TMP_mrb_#{gem_name.tr('-', '_')}_gem_init"
end

def sync_gem_sources(gem_name, dest_root)
  src_gem = MRUBY.join("mrbgems", gem_name)
  raise "missing gem #{gem_name}" unless src_gem.directory?

  dest_gem = dest_root.join("mrbgems", gem_name)
  %w[src include core].each do |sub|
    from = src_gem.join(sub)
    next unless from.directory?

    FileUtils.rm_rf(dest_gem.join(sub))
    FileUtils.mkdir_p(dest_gem)
    FileUtils.cp_r(from, dest_gem.join(sub))
  end
end

def sync_gem_init(gem_name, dest_root)
  generated = HOST_VM_BUILD.join("mrbgems", gem_name, "gem_init.c")
  raise "missing generated init for #{gem_name}; build host_vm first" unless generated.file?

  dest = dest_root.join("build_host/mrbgems", gem_name)
  FileUtils.mkdir_p(dest)
  FileUtils.cp(generated, dest.join("gem_init.c"))
end

def gems_init_source
  lines = []
  lines << "/* Generated by tools/sync_device_mruby_gems.rb -- do not edit. */"
  lines << "#include <mruby.h>"
  lines << ""
  HAL_GEMS.each { |gem| lines << "void mrb_#{gem.tr('-', '_')}_gem_init(mrb_state *mrb);" }
  CORE_GEMS.each { |gem| lines << "void #{gem_init_symbol(gem)}(mrb_state *mrb);" }
  NATIVE_RUBY_GEMS.each { |gem| lines << "void #{gem_init_symbol(gem)}(mrb_state *mrb);" }
  PRELOADED_RUBY_GEMS.each { |gem| lines << "void #{gem_init_symbol(gem)}(mrb_state *mrb);" }
  lines << "void mrb_mruby_digest_gem_init(mrb_state *mrb);"
  lines << ""
  lines << "void"
  lines << "mrb_init_mrbgems(mrb_state *mrb)"
  lines << "{"
  HAL_GEMS.each { |gem| lines << "  mrb_#{gem.tr('-', '_')}_gem_init(mrb);" }
  CORE_GEMS.each { |gem| lines << "  #{gem_init_symbol(gem)}(mrb);" }
  lines << "  mrb_mruby_digest_gem_init(mrb);"
  NATIVE_RUBY_GEMS.each { |gem| lines << "  #{gem_init_symbol(gem)}(mrb);" }
  PRELOADED_RUBY_GEMS.each { |gem| lines << "  #{gem_init_symbol(gem)}(mrb);" }
  lines << "}"
  lines.join("\n") + "\n"
end

PLATFORM_TARGETS.each do |platform, mruby_src|
  raise "missing #{mruby_src}" unless mruby_src.directory?

  generated_presym = HOST_VM_BUILD.join("include/mruby/presym")
  raise "missing generated presym headers; build host_vm first" unless generated_presym.directory?
  platform_presym = mruby_src.join("include/mruby/presym")
  FileUtils.rm_rf(platform_presym)
  FileUtils.mkdir_p(platform_presym.parent)
  FileUtils.cp_r(generated_presym, platform_presym)

  (CORE_GEMS + CORE_SOURCE_GEMS + HAL_GEMS).each { |gem| sync_gem_sources(gem, mruby_src) }
  CORE_GEMS.each { |gem| sync_gem_init(gem, mruby_src) }
  NATIVE_RUBY_GEMS.each { |gem| sync_gem_init(gem, mruby_src) }
  PRELOADED_RUBY_GEMS.each { |gem| sync_gem_init(gem, mruby_src) }

  init_file = mruby_src.parent.join(platform == "macos" ? "Classes/mruby_gems_init.c" : "Classes/mruby_gems_init.c")
  init_file.write(gems_init_source)
  puts "Synced #{CORE_GEMS.length + CORE_SOURCE_GEMS.length + HAL_GEMS.length} gems -> #{mruby_src.relative_path_from(ROOT)}"
end

shared_init = ROOT.join("ruby_runtime/shared/mruby_gems_init.c")
shared_init.write(gems_init_source)
puts "Wrote #{shared_init.relative_path_from(ROOT)}"

puts "\nPodspec source globs needed:"
puts "  mruby_src/mrbgems/{#{(CORE_GEMS + HAL_GEMS).join(',')}}/src/*.c"
puts "  mruby_src/mrbgems/mruby-bigint/core/*.c"
puts "  mruby_src/build_host/mrbgems/{#{(CORE_GEMS + NATIVE_RUBY_GEMS + PRELOADED_RUBY_GEMS).join(',')}}/gem_init.c"
